[WIP] Making WarBot a webpage - adding flask
RiLeone/warbot pull request #28
Opened 2020-09-27 22:27 UTC by mafilipp

Still WIP

2020-09-27 22:33 UTC, mafilipp commented
@RiLeone  I thought that for the world selection it would be nice to have a drop down. How would you suggest me to integrate it with WorldSelector? Imo I could just have a mapping
name_world -> file_to_select.json
What do you think?

2020-09-28 06:33 UTC, RiLeone commented on app.py
> +    world_file = './worlds/Debugland/states.json'
For using the drop-down  menu (which I really like, in particular in the web-oriented approach) I would use the `AuxiliaryTools.list_worlds()` function here or just before generating the dropdown to get all available worlds (each world then is required to have a `states.josn` file in any case to work).

2020-09-28 06:36 UTC, RiLeone commented on app.py
> +    return render_template('home.html', text=text, bold_text=bold_text)
I peresoanlly prefer packing all kwargs in a dictionary and then pass the **dict as single argument to `render_template()`, but this is purely personal preference :)

2020-09-28 06:40 UTC, RiLeone commented on templates/home.html
> +    <h1>{{bold_text}}</h1>
I would have called it `title` instead of `bold_text`, but again, this is only personal preference.

2020-09-28 06:47 UTC, RiLeone requested changes
IMO it is better if we wait for your suggestions (drop-down, rpoper text formatting, replacement of placehodelrs with "meaningful" text) to be implemented before merging, so that the merged version already has all basic features we want and does not contain any palceholders anymore. Would that be ok for you? Also, could you also add a basic shell script for running the flask app (in`x/`)? I know, right now it would be a single-line file, but later on, if we have some args to pass we already have a flexiblesolution in place.

2020-09-28 19:57 UTC, mafilipp commented on app.py
> +    return render_template('home.html', text=text, bold_text=bold_text)
This is actually what is happening. Indeed, the function offered by flask API is:
`def render_template(template_name_or_list, **context)`

2020-09-28 20:07 UTC, mafilipp commented on app.py
> +    return render_template('home.html', text=text, bold_text=bold_text)
In general, I agree definitely with you, it keeps the code cleaner

2020-09-28 20:32 UTC, mafilipp commented
I updated my PR @RiLeone. IMO like that is finished and could be merged, after your review of course :)
Let me know what do you think.
About your suggestion on the script to start flask, I can imagine you mean something like [that](https://stackoverflow.com/a/41264536). I am not sure though if we should give the possibility of command-line arguments. imo the app should be started just once, and everything that we can change on the webpage should be configurable on the webpage.. what do you think?

Thank you for the review

2020-09-28 20:35 UTC, mafilipp commented on app.py
> +    world_file = './worlds/Debugland/states.json'
Thank you for the suggestion

2020-09-29 06:30 UTC, merged

2020-09-29 06:33 UTC, RiLeone commented
> I updated my PR @RiLeone. IMO like that is finished and could be merged, after your review of course :)
> Let me know what do you think.
> About your suggestion on the script to start flask, I can imagine you mean something like [that](https://stackoverflow.com/a/41264536). I am not sure though if we should give the possibility of command-line arguments. imo the app should be started just once, and everything that we can change on the webpage should be configurable on the webpage.. what do you think?
> 
> Thank you for the review

I was more thinking of a shell-script (probably a single liner), but you are right. Let's keep it like it is now :D

2020-09-29 06:35 UTC, RiLeone reviewed
All good